
replicaCount: 3

namespace: devops-project

podLabels:
  app: tic-tac-toe

nameOverride: tic-tac-toe
fullnameOverride: tic-tac-toe

image:
  repository: ghcr.io/suhas-005/devops-pipeline
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
  periodSeconds: 10
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  protocol: TCP