apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "chart.fullname" . }}
  labels:
  {{- range $key, $value := .Values.podLabels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- range $key, $value := .Values.podLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- range $key, $value := .Values.podLabels }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
      {{- end }}
    spec:
      containers:
        name: {{ include "chart.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.PullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}