{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "chart.fullname" . }}-ingress
  labels:
  {{- range $key, $value := .Values.podLabels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: {{ .Values.ingress.servicePort}}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
{{- end }}