name: Run checks/tests

on:
  pull_request:
    types: 
      - opened
    branches:
      - main
    paths: app-codebase/**

jobs:
  test:
    name: Linting and Unit Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: app-codebase
        run: npm ci

      - name: Run lint
        working-directory: app-codebase
        run: npm run lint

      - name: Run tests
        working-directory: app-codebase
        run: npm run test